# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('number', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.IntegerField(default=0)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('O', 'Open'), ('C', 'Closed'), ('S', 'Suspended')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('is_done', models.BooleanField(default=False)),
                ('target_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('is_employee', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('ticket_employee', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankingSystem.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('A', 'Under Approval'), ('P', 'Processed'), ('I', 'Insufficient Funds'), ('E', 'Unknown Error')], max_length=1)),
                ('is_cash', models.BooleanField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_changed_time', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.Profile')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='BankingSystem.Account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='BankingSystem.Account')),
            ],
        ),
        migrations.AddField(
            model_name='payments',
            name='target_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.Profile'),
        ),
        migrations.AddField(
            model_name='payments',
            name='transaction',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.Transactions'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankingSystem.Profile'),
        ),
    ]
