# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('user_operations', 'Has permission to own an account, do account operations'), ('create_payments', 'For merchants to create payments for their users'), ('employee_operations', 'Has permissions to check the employee dashboard'), ('view_critical_transactions', 'Manager/Staff, has permission to mark critical transactions'), ('super_perm', 'For debug and superuser purposes'))},
        ),
    ]
