# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0003_auto_20171101_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankingSystem.Profile'),
        ),
        migrations.AlterField(
            model_name='payments',
            name='transaction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='BankingSystem.Transactions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ticket_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankingSystem.Profile'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_account', to='BankingSystem.Account'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_account', to='BankingSystem.Account'),
        ),
    ]
