# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0004_auto_20171101_2118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_employee',
        ),
        migrations.AlterField(
            model_name='profile',
            name='ticket_employee',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_ticket', to='BankingSystem.Profile'),
        ),
    ]
