# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 02:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0006_auto_20171103_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='BankingSystem.Profile'),
        ),
    ]
