# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 19:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankingSystem', '0007_auto_20171103_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='target_account',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='target_user',
        ),
        migrations.AddField(
            model_name='payments',
            name='merchant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_merchant', to='BankingSystem.Profile'),
        ),
        migrations.AddField(
            model_name='payments',
            name='user_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_user', to='BankingSystem.Account'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[('C', 'Created'), ('A', 'Under_Approval'), ('P', 'Processed'), ('R', 'Rejected'), ('I', 'Insufficient_Funds'), ('E', 'Error')], max_length=1),
        ),
    ]
